# -*- coding: utf-8 -*-
from __future__ import annotations

# Libellés FR abrégés (clés = shortName/keys internes côté serveur)
FR_BY_KEY: dict[str, str] = {
    # ---------------- GPS & télémétrie ----------------
    "gpslat": "Lat. GPS",
    "gpslon": "Lon. GPS",
    "gps_height": "Alt. GPS",
    "gps_acc": "Préc. GPS",
    "gps_sats": "Sat. GPS",
    "gps_bearing": "Cap GPS",
    "gps_bearing_legacy_ff1007": "Cap GPS (legacy)",
    "gps_spd": "Vit. GPS",

    # ---------------- OBD-II standard ----------------
    "engine_load": "Charge mot.",
    "coolant_temp": "Eau°",
    "fuel_trim_b1_short": "Ajust B1 CT",
    "fuel_trim_b1_long": "Ajust B1 LT",
    "fuel_trim_b2_short": "Ajust B2 CT",
    "fuel_trim_b2_long": "Ajust B2 LT",
    "fuel_pressure": "Press. carbu.",
    "intake_manifold_pressure": "Press. adm.",
    "engine_rpm": "Rég.",

    "speed_obd": "Vit. OBD",
    "speed": "Vit.",

    "timing_advance": "Avance°",
    "intake_air_temp": "T° adm.",
    "mass_air_flow_rate": "Débit air",
    "throttle_position_manifold": "Papillon",
    "fuel_trim_o2l_1": "Ajust O2L:1",
    "fuel_trim_o2l_2": "Ajust O2L:2",
    "fuel_trim_o2l_3": "Ajust O2L:3",
    "fuel_trim_o2l_4": "Ajust O2L:4",
    "fuel_trim_o2l_5": "Ajust O2L:5",
    "fuel_trim_o2l_6": "Ajust O2L:6",
    "fuel_trim_o2l_7": "Ajust O2L:7",
    "fuel_trim_o2l_8": "Ajust O2L:8",
    "run_time_since_start": "Temps depuis dém.",
    "dist_mil_on": "Dist. MIL on",
    "fuel_rail_pressure_rel": "Press. rampe rel.",
    "fuel_rail_pressure": "Press. rampe",
    "o2_o2l1_wide_voltage": "Tens. O₂ {O2L:1} (LB)",
    "o2_o2l2_wide_voltage": "Tens. O₂ {O2L:2} (LB)",
    "o2_o2l3_wide_voltage": "Tens. O₂ {O2L:3} (LB)",
    "o2_o2l4_wide_voltage": "Tens. O₂ {O2L:4} (LB)",
    "o2_o2l5_wide_voltage": "Tens. O₂ {O2L:5} (LB)",
    "o2_o2l6_wide_voltage": "Tens. O₂ {O2L:6} (LB)",
    "o2_o2l7_wide_voltage": "Tens. O₂ {O2L:7} (LB)",
    "o2_o2l8_wide_voltage": "Tens. O₂ {O2L:8} (LB)",
    "egr_commanded": "EGR cmd.",
    "egr_error": "Err. EGR",
    "fuel_level_ecu": "Niv. carbu.",
    "dist_since_codes_cleared": "Dist. après effacement",
    "evap_system_vapour_pressure": "Press. EVAP",
    "barometric_pressure_vehicle": "Press. baro.",
    "o2_o2l1_wide_current": "Cour. O₂ {O2L:1} (LB)",
    "o2_o2l2_wide_current": "Cour. O₂ {O2L:2} (LB)",
    "o2_o2l3_wide_current": "Cour. O₂ {O2L:3} (LB)",
    "o2_o2l4_wide_current": "Cour. O₂ {O2L:4} (LB)",
    "o2_o2l5_wide_current": "Cour. O₂ {O2L:5} (LB)",
    "o2_o2l6_wide_current": "Cour. O₂ {O2L:6} (LB)",
    "o2_o2l7_wide_current": "Cour. O₂ {O2L:7} (LB)",
    "o2_o2l8_wide_current": "Cour. O₂ {O2L:8} (LB)",
    "cat_temp_b1s1": "T° cat. B1S1",
    "cat_temp_b2s1": "T° cat. B2S1",
    "cat_temp_b1s2": "T° cat. B1S2",
    "cat_temp_b2s2": "T° cat. B2S2",
    "voltage_control_module": "Tension ECU",
    "engine_load_absolute": "Charge abs.",
    "commanded_equivalence_ratio": "λ cmd.",
    "relative_throttle_position": "Papillon rel.",
    "ambient_air_temp": "T° ext.",
    "absolute_throttle_position_b": "Papillon abs. B",
    "accelerator_pedal_pos_d": "Pédale D",
    "accelerator_pedal_pos_e": "Pédale E",
    "accelerator_pedal_pos_f": "Pédale F",
    "ethanol_fuel_pct": "Éthanol %",
    "relative_accelerator_pedal_position": "Pédale rel.",
    "hybrid_ev_batt_charge": "Batt. HV %",
    "engine_oil_temperature": "Huile°",
    "fuel_rate_ecu": "Débit carbu.",
    "driver_demand_engine_torque_pct": "Couple demandé",
    "actual_engine_torque_pct": "Couple réel",
    "engine_reference_torque": "Couple réf.",
    "maf_sensor_a": "MAF A",
    "boost_pressure_commanded_a": "Boost cmd. A",
    "exhaust_pressure_b1": "Press. éch. B1",
    "charge_air_cooler_temp": "T° après échangeur",
    "egt_b1_s1": "T° EGT B1S1",
    "egt_b2_s1": "T° EGT B2S1",
    "dpf_b1_delta_pressure": "ΔP FAP B1",
    "dpf_b2_delta_pressure": "ΔP FAP B2",
    "dpf_b1_inlet_temp": "T° entrée FAP B1",
    "nox_pre_scr": "NOx avant SCR",
    "intake_manifold_abs_pressure_a": "Press. adm. abs. A",
    "hybrid_ev_batt_voltage": "Tens. batt. HV",
    "odometer_ecu": "Odomètre",
    "hybrid_ev_batt_soh": "SOH batt. HV",
    "transmission_temp_method_2": "T° boîte (M2)",

    # ---------------- FF10xx / FF12xx divers ----------------
    "mpg_instant": "MPG inst.",
    "turbo_boost_vacuum_gauge": "Boost/dépr. turbo",
    "kpl_instant": "km/L inst.",
    "trip_distance": "Dist. trajet",
    "mpg_trip_avg": "MPG moy.",
    "kpl_trip_avg": "km/L moy.",
    "l_per_100_instant": "L/100 inst.",
    "l_per_100_trip_avg": "L/100 moy.",
    "trip_distance_stored": "Dist. trajet (profil)",
    "accel_x": "Accél. X",
    "accel_y": "Accél. Y",
    "accel_z": "Accél. Z",
    "accel_total": "Accél. tot.",
    "torque": "Couple roues",
    "horsepower_wheels": "Puiss. roues hp",
    "time_0_60mph": "0–60 mph",
    "time_0_100kph": "0–100 km/h",
    "time_quarter_mile": "1/4 mile",
    "time_eighth_mile": "1/8 mile",
    "spd_diff_gps_obd": "Écart GPS/OBD",
    "voltage_obd_adapter": "Tension OBD",
    "o2_o2l1_wide_eq_ratio": "λ O₂ {O2L:1}",
    "o2_o2l2_wide_eq_ratio": "λ O₂ {O2L:2}",
    "o2_o2l3_wide_eq_ratio": "λ O₂ {O2L:3}",
    "o2_o2l4_wide_eq_ratio": "λ O₂ {O2L:4}",
    "o2_o2l5_wide_eq_ratio": "λ O₂ {O2L:5}",
    "o2_o2l6_wide_eq_ratio": "λ O₂ {O2L:6}",
    "o2_o2l7_wide_eq_ratio": "λ O₂ {O2L:7}",
    "o2_o2l8_wide_eq_ratio": "λ O₂ {O2L:8}",
    "air_fuel_ratio_measured": "AFR mes.",
    "air_fuel_ratio_commanded": "AFR cmd.",
    "time_0_200kph": "0–200 km/h",
    "co2_gkm_instant": "CO₂ g/km inst.",
    "co2_gkm_avg": "CO₂ g/km moy.",
    "fuel_flow_rate_min": "Débit carbu. cc/min",
    "fuel_cost_trip": "Coût trajet",
    "fuel_flow_rate_hr": "Débit carbu. L/h",
    "time_60_120mph": "60–120 mph",
    "time_60_80mph": "60–80 mph",
    "time_40_60mph": "40–60 mph",
    "time_80_100mph": "80–100 mph",
    "avg_trip_speed_moving": "Vit. moy. (roul.)",
    "time_100_0kph": "100–0 km/h",
    "time_60_0mph": "60–0 mph",
    "trip_time_since_start": "Temps trajet",
    "trip_time_stationary": "Temps à l’arrêt",
    "trip_time_moving": "Temps en mouv.",
    "volumetric_efficiency_calc": "Rend. vol. calc.",
    "distance_to_empty_est": "Autonomie (estim.)",
    "fuel_remaining_calc": "Carb. restant (calc.)",
    "cost_per_km_instant": "Coût/km inst.",
    "cost_per_km_trip": "Coût/km trajet",
    "barometer_android": "Baromètre",
    "fuel_used_trip": "Carb. utilisé",
    "avg_trip_speed_overall": "Vit. moy. (glob.)",
    "engine_kw_wheels": "Puiss. kW (roues)",
    "time_80_120kph": "80–120 km/h",
    "time_60_130mph": "60–130 mph",
    "time_0_30mph": "0–30 mph",
    "time_0_100mph": "0–100 mph",
    "time_100_200kph": "100–200 km/h",
    "egt_b1_s2": "T° EGT B1S2",
    "egt_b1_s3": "T° EGT B1S3",
    "egt_b1_s4": "T° EGT B1S4",
    "egt_b2_s2": "T° EGT B2S2",
    "egt_b2_s3": "T° EGT B2S3",
    "egt_b2_s4": "T° EGT B2S4",
    "nox_post_scr": "NOx après SCR",
    "pct_city_driving": "Part ville",
    "pct_highway_driving": "Part voie rapide",
    "pct_idle_driving": "Part ralenti",
    "android_battery_level": "Batterie Android",
    "dpf_b1_outlet_temp": "T° sortie FAP B1",
    "dpf_b2_inlet_temp": "T° entrée FAP B2",
    "dpf_b2_outlet_temp": "T° sortie FAP B2",
    "maf_sensor_b": "MAF B",

    # ---------------- FF12A* – Pression/Boost (B) ----------------
    "intake_manifold_abs_pressure_b": "Press. adm. abs. B",
    "boost_pressure_commanded_b": "Boost cmd. B",
    "boost_pressure_sensor_a": "Capteur boost A",
    "boost_pressure_sensor_b": "Capteur boost B",
    "exhaust_pressure_b2": "Press. éch. B2",

    # ---------------- FF12B* – DPF & Hybrid/EV ----------------
    "dpf_b1_inlet_pressure": "Press. entrée FAP B1",
    "dpf_b1_outlet_pressure": "Press. sortie FAP B1",
    "dpf_b2_inlet_pressure": "Press. entrée FAP B2",
    "dpf_b2_outlet_pressure": "Press. sortie FAP B2",
    "hybrid_ev_batt_current": "Cour. batt. HV",
    "hybrid_ev_batt_power": "Puiss. batt. HV",
    "positive_kinetic_energy_pke": "Énergie cinét. + (PKE)",

    # ---------------- FF52xx – Moyennes LT ----------------
    "mpg_long_term_avg": "MPG moy. LT",
    "kpl_long_term_avg": "km/L moy. LT",
    "l_per_100_long_term_avg": "L/100 moy. LT",

    # ---------------- Aliases historiques utiles ----------------
    "intake_temp": "T° adm.",
    "throttle_pos": "Papillon",
    "volumetric_efficiency_calculated": "Rend. vol. calc.",
    "co2_in_gkm_average": "CO₂ g/km moy.",
    "co2_in_gkm_instantaneous": "CO₂ g/km inst.",
    "cost_per_milekm_instant": "Coût/km/mile inst.",
    "cost_per_milekm_trip": "Coût/km/mile trajet",
    "trip_average_kpl": "km/L moy. trajet",
    "trip_average_litres100_km": "L/100 moy. trajet",
    "trip_average_litres100km": "L/100 moy. trajet",
    "trip_average_mpg": "MPG moy. trajet",
    "distance_du_trajet": "Dist. trajet",
    "trip_distance_stored_in_vehicle_profile": "Dist. trajet (profil)",

    # Anciennes clés de temps (si jamais présentes)
    "0_60mph_time": "0–60 mph",
    "0_100kph_time": "0–100 km/h",
    "40_60mph_time": "40–60 mph",
    "60_0mph_time": "60–0 mph",
    "60_80mph_time": "60–80 mph",
    "60_120mph_time": "60–120 mph",
    "60_130mph_time": "60–130 mph",
    "80_120kph_time": "80–120 km/h",
    "100_0kph_time": "100–0 km/h",
    "100_200kph_time": "100–200 km/h",
}
